# Generated by Django 6.0.1 on 2026-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='assigned_donor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
